version: '2.3'
services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    links:
      - mongo
    volumes:
      - ./notebooks:/home/jovyan/notebooks

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
